# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.srcs/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.xci
# IP: The module: 'qdma_hbm_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.srcs/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.xci
# IP: The module: 'qdma_hbm_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qdma_hbm_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
