// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2024.2 (lin64) Build 5239630 Fri Nov 08 22:34:34 MST 2024
// Date        : Wed Mar 26 16:48:15 2025
// Host        : ogreOptiPlex running 64-bit Ubuntu 22.04.5 LTS
// Command     : write_verilog -force -mode synth_stub
//               /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/qdma_hbm_bd_hbm_0_0_stub.v
// Design      : qdma_hbm_bd_hbm_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xcu55c-fsvh2892-2L-e
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* CHECK_LICENSE_TYPE = "qdma_hbm_bd_hbm_0_0,hbm_v1_0_16,{}" *) (* CORE_GENERATION_INFO = "qdma_hbm_bd_hbm_0_0,hbm_v1_0_16,{x_ipProduct=Vivado 2024.2,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=hbm,x_ipVersion=1.0,x_ipCoreRevision=16,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,HBM_STACK=2,SWITCH_ENABLE_00=TRUE,SWITCH_ENABLE_01=TRUE,INIT_BYPASS=FALSE,INIT_SEQ_TIMEOUT=10000000,AXI_RST_ASSERT_WIDTH=16,AXI_RST_DEASSERT_WIDTH=2,TEMP_WAIT_PERIOD_0=100000,TEMP_WAIT_PERIOD_1=100000,SWITCH_EN_0=1,SWITCH_EN_1=1,AXI_CLK_FREQ=450,AXI_CLK1_FREQ=450,HBM_REF_CLK_FREQ_0=100,HBM_REF_CLK_FREQ_1=100,HBM_CLK_FREQ_0=900,HBM_CLK_FREQ_1=900,HBM_STACK_NUM=0,CLK_SEL_00=FALSE,CLK_SEL_01=FALSE,CLK_SEL_02=FALSE,CLK_SEL_03=FALSE,CLK_SEL_04=FALSE,CLK_SEL_05=FALSE,CLK_SEL_06=FALSE,CLK_SEL_07=FALSE,CLK_SEL_08=FALSE,CLK_SEL_09=FALSE,CLK_SEL_10=FALSE,CLK_SEL_11=FALSE,CLK_SEL_12=FALSE,CLK_SEL_13=FALSE,CLK_SEL_14=FALSE,CLK_SEL_15=TRUE,CLK_SEL_16=TRUE,CLK_SEL_17=FALSE,CLK_SEL_18=FALSE,CLK_SEL_19=FALSE,CLK_SEL_20=FALSE,CLK_SEL_21=FALSE,CLK_SEL_22=FALSE,CLK_SEL_23=FALSE,CLK_SEL_24=FALSE,CLK_SEL_25=FALSE,CLK_SEL_26=FALSE,CLK_SEL_27=FALSE,CLK_SEL_28=FALSE,CLK_SEL_29=FALSE,CLK_SEL_30=FALSE,CLK_SEL_31=FALSE,DATARATE_STACK_0=1800,DATARATE_STACK_1=1800,READ_PERCENT_00=40,READ_PERCENT_01=40,READ_PERCENT_02=40,READ_PERCENT_03=40,READ_PERCENT_04=40,READ_PERCENT_05=40,READ_PERCENT_06=40,READ_PERCENT_07=40,READ_PERCENT_08=40,READ_PERCENT_09=40,READ_PERCENT_10=40,READ_PERCENT_11=40,READ_PERCENT_12=40,READ_PERCENT_13=40,READ_PERCENT_14=40,READ_PERCENT_15=40,READ_PERCENT_16=40,READ_PERCENT_17=40,READ_PERCENT_18=40,READ_PERCENT_19=40,READ_PERCENT_20=40,READ_PERCENT_21=40,READ_PERCENT_22=40,READ_PERCENT_23=40,READ_PERCENT_24=40,READ_PERCENT_25=40,READ_PERCENT_26=40,READ_PERCENT_27=40,READ_PERCENT_28=40,READ_PERCENT_29=40,READ_PERCENT_30=40,READ_PERCENT_31=40,WRITE_PERCENT_00=40,WRITE_PERCENT_01=40,WRITE_PERCENT_02=40,WRITE_PERCENT_03=40,WRITE_PERCENT_04=40,WRITE_PERCENT_05=40,WRITE_PERCENT_06=40,WRITE_PERCENT_07=40,WRITE_PERCENT_08=40,WRITE_PERCENT_09=40,WRITE_PERCENT_10=40,WRITE_PERCENT_11=40,WRITE_PERCENT_12=40,WRITE_PERCENT_13=40,WRITE_PERCENT_14=40,WRITE_PERCENT_15=40,WRITE_PERCENT_16=40,WRITE_PERCENT_17=40,WRITE_PERCENT_18=40,WRITE_PERCENT_19=40,WRITE_PERCENT_20=40,WRITE_PERCENT_21=40,WRITE_PERCENT_22=40,WRITE_PERCENT_23=40,WRITE_PERCENT_24=40,WRITE_PERCENT_25=40,WRITE_PERCENT_26=40,WRITE_PERCENT_27=40,WRITE_PERCENT_28=40,WRITE_PERCENT_29=40,WRITE_PERCENT_30=40,WRITE_PERCENT_31=40,PAGEHIT_PERCENT_00=75,PAGEHIT_PERCENT_01=75,MC_ENABLE_00=TRUE,MC_ENABLE_01=TRUE,MC_ENABLE_02=TRUE,MC_ENABLE_03=TRUE,MC_ENABLE_04=TRUE,MC_ENABLE_05=TRUE,MC_ENABLE_06=TRUE,MC_ENABLE_07=TRUE,MC_ENABLE_08=TRUE,MC_ENABLE_09=TRUE,MC_ENABLE_10=TRUE,MC_ENABLE_11=TRUE,MC_ENABLE_12=TRUE,MC_ENABLE_13=TRUE,MC_ENABLE_14=TRUE,MC_ENABLE_15=TRUE,MC_ENABLE_APB_00=TRUE,MC_ENABLE_APB_01=TRUE,PHY_ENABLE_00=TRUE,PHY_ENABLE_01=TRUE,PHY_ENABLE_02=TRUE,PHY_ENABLE_03=TRUE,PHY_ENABLE_04=TRUE,PHY_ENABLE_05=TRUE,PHY_ENABLE_06=TRUE,PHY_ENABLE_07=TRUE,PHY_ENABLE_08=TRUE,PHY_ENABLE_09=TRUE,PHY_ENABLE_10=TRUE,PHY_ENABLE_11=TRUE,PHY_ENABLE_12=TRUE,PHY_ENABLE_13=TRUE,PHY_ENABLE_14=TRUE,PHY_ENABLE_15=TRUE,PHY_ENABLE_16=TRUE,PHY_ENABLE_17=TRUE,PHY_ENABLE_18=TRUE,PHY_ENABLE_19=TRUE,PHY_ENABLE_20=TRUE,PHY_ENABLE_21=TRUE,PHY_ENABLE_22=TRUE,PHY_ENABLE_23=TRUE,PHY_ENABLE_24=TRUE,PHY_ENABLE_25=TRUE,PHY_ENABLE_26=TRUE,PHY_ENABLE_27=TRUE,PHY_ENABLE_28=TRUE,PHY_ENABLE_29=TRUE,PHY_ENABLE_30=TRUE,PHY_ENABLE_31=TRUE,PHY_ENABLE_APB_00=TRUE,PHY_ENABLE_APB_01=TRUE}" *) (* DowngradeIPIdentifiedWarnings = "yes" *) 
(* X_CORE_INFO = "hbm_v1_0_16,Vivado 2024.2" *) 
module qdma_hbm_bd_hbm_0_0(HBM_REF_CLK_0, HBM_REF_CLK_1, AXI_15_ACLK, 
  AXI_15_ARESET_N, AXI_15_ARADDR, AXI_15_ARBURST, AXI_15_ARID, AXI_15_ARLEN, AXI_15_ARSIZE, 
  AXI_15_ARVALID, AXI_15_AWADDR, AXI_15_AWBURST, AXI_15_AWID, AXI_15_AWLEN, AXI_15_AWSIZE, 
  AXI_15_AWVALID, AXI_15_RREADY, AXI_15_BREADY, AXI_15_WDATA, AXI_15_WLAST, AXI_15_WSTRB, 
  AXI_15_WDATA_PARITY, AXI_15_WVALID, AXI_16_ACLK, AXI_16_ARESET_N, AXI_16_ARADDR, 
  AXI_16_ARBURST, AXI_16_ARID, AXI_16_ARLEN, AXI_16_ARSIZE, AXI_16_ARVALID, AXI_16_AWADDR, 
  AXI_16_AWBURST, AXI_16_AWID, AXI_16_AWLEN, AXI_16_AWSIZE, AXI_16_AWVALID, AXI_16_RREADY, 
  AXI_16_BREADY, AXI_16_WDATA, AXI_16_WLAST, AXI_16_WSTRB, AXI_16_WDATA_PARITY, 
  AXI_16_WVALID, APB_0_PCLK, APB_0_PRESET_N, APB_1_PCLK, APB_1_PRESET_N, AXI_15_ARREADY, 
  AXI_15_AWREADY, AXI_15_RDATA_PARITY, AXI_15_RDATA, AXI_15_RID, AXI_15_RLAST, AXI_15_RRESP, 
  AXI_15_RVALID, AXI_15_WREADY, AXI_15_BID, AXI_15_BRESP, AXI_15_BVALID, AXI_16_ARREADY, 
  AXI_16_AWREADY, AXI_16_RDATA_PARITY, AXI_16_RDATA, AXI_16_RID, AXI_16_RLAST, AXI_16_RRESP, 
  AXI_16_RVALID, AXI_16_WREADY, AXI_16_BID, AXI_16_BRESP, AXI_16_BVALID, apb_complete_0, 
  apb_complete_1, DRAM_0_STAT_CATTRIP, DRAM_0_STAT_TEMP, DRAM_1_STAT_CATTRIP, 
  DRAM_1_STAT_TEMP)
/* synthesis syn_black_box black_box_pad_pin="HBM_REF_CLK_0,HBM_REF_CLK_1,AXI_15_ARESET_N,AXI_15_ARADDR[33:0],AXI_15_ARBURST[1:0],AXI_15_ARID[5:0],AXI_15_ARLEN[3:0],AXI_15_ARSIZE[2:0],AXI_15_ARVALID,AXI_15_AWADDR[33:0],AXI_15_AWBURST[1:0],AXI_15_AWID[5:0],AXI_15_AWLEN[3:0],AXI_15_AWSIZE[2:0],AXI_15_AWVALID,AXI_15_RREADY,AXI_15_BREADY,AXI_15_WDATA[255:0],AXI_15_WLAST,AXI_15_WSTRB[31:0],AXI_15_WDATA_PARITY[31:0],AXI_15_WVALID,AXI_16_ARESET_N,AXI_16_ARADDR[33:0],AXI_16_ARBURST[1:0],AXI_16_ARID[5:0],AXI_16_ARLEN[3:0],AXI_16_ARSIZE[2:0],AXI_16_ARVALID,AXI_16_AWADDR[33:0],AXI_16_AWBURST[1:0],AXI_16_AWID[5:0],AXI_16_AWLEN[3:0],AXI_16_AWSIZE[2:0],AXI_16_AWVALID,AXI_16_RREADY,AXI_16_BREADY,AXI_16_WDATA[255:0],AXI_16_WLAST,AXI_16_WSTRB[31:0],AXI_16_WDATA_PARITY[31:0],AXI_16_WVALID,APB_0_PRESET_N,APB_1_PRESET_N,AXI_15_ARREADY,AXI_15_AWREADY,AXI_15_RDATA_PARITY[31:0],AXI_15_RDATA[255:0],AXI_15_RID[5:0],AXI_15_RLAST,AXI_15_RRESP[1:0],AXI_15_RVALID,AXI_15_WREADY,AXI_15_BID[5:0],AXI_15_BRESP[1:0],AXI_15_BVALID,AXI_16_ARREADY,AXI_16_AWREADY,AXI_16_RDATA_PARITY[31:0],AXI_16_RDATA[255:0],AXI_16_RID[5:0],AXI_16_RLAST,AXI_16_RRESP[1:0],AXI_16_RVALID,AXI_16_WREADY,AXI_16_BID[5:0],AXI_16_BRESP[1:0],AXI_16_BVALID,apb_complete_0,apb_complete_1,DRAM_0_STAT_CATTRIP,DRAM_0_STAT_TEMP[6:0],DRAM_1_STAT_CATTRIP,DRAM_1_STAT_TEMP[6:0]" */
/* synthesis syn_force_seq_prim="AXI_15_ACLK" */
/* synthesis syn_force_seq_prim="AXI_16_ACLK" */
/* synthesis syn_force_seq_prim="APB_0_PCLK" */
/* synthesis syn_force_seq_prim="APB_1_PCLK" */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 HBM_REF_CLK_0 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME HBM_REF_CLK_0, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input HBM_REF_CLK_0;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 HBM_REF_CLK_1 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME HBM_REF_CLK_1, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input HBM_REF_CLK_1;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_15_8HI CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_15_8HI, ASSOCIATED_BUSIF SAXI_15_8HI, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_aclk_0, INSERT_VIP 0" *) input AXI_15_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_15_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_15_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_15_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_15_8HI, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 34, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_aclk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [33:0]AXI_15_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARBURST" *) input [1:0]AXI_15_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARID" *) input [5:0]AXI_15_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARLEN" *) input [3:0]AXI_15_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARSIZE" *) input [2:0]AXI_15_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARVALID" *) input AXI_15_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWADDR" *) input [33:0]AXI_15_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWBURST" *) input [1:0]AXI_15_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWID" *) input [5:0]AXI_15_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWLEN" *) input [3:0]AXI_15_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWSIZE" *) input [2:0]AXI_15_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWVALID" *) input AXI_15_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RREADY" *) input AXI_15_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI BREADY" *) input AXI_15_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI WDATA" *) input [255:0]AXI_15_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI WLAST" *) input AXI_15_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI WSTRB" *) input [31:0]AXI_15_WSTRB;
  input [31:0]AXI_15_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI WVALID" *) input AXI_15_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ACLK_16_8HI CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ACLK_16_8HI, ASSOCIATED_BUSIF SAXI_16_8HI, FREQ_HZ 250000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_aclk_0, INSERT_VIP 0" *) input AXI_16_ACLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ARST_16_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME ARST_16_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input AXI_16_ARESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARADDR" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME SAXI_16_8HI, DATA_WIDTH 256, PROTOCOL AXI3, FREQ_HZ 250000000, ID_WIDTH 6, ADDR_WIDTH 34, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_aclk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) input [33:0]AXI_16_ARADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARBURST" *) input [1:0]AXI_16_ARBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARID" *) input [5:0]AXI_16_ARID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARLEN" *) input [3:0]AXI_16_ARLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARSIZE" *) input [2:0]AXI_16_ARSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARVALID" *) input AXI_16_ARVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWADDR" *) input [33:0]AXI_16_AWADDR;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWBURST" *) input [1:0]AXI_16_AWBURST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWID" *) input [5:0]AXI_16_AWID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWLEN" *) input [3:0]AXI_16_AWLEN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWSIZE" *) input [2:0]AXI_16_AWSIZE;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWVALID" *) input AXI_16_AWVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RREADY" *) input AXI_16_RREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI BREADY" *) input AXI_16_BREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI WDATA" *) input [255:0]AXI_16_WDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI WLAST" *) input AXI_16_WLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI WSTRB" *) input [31:0]AXI_16_WSTRB;
  input [31:0]AXI_16_WDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI WVALID" *) input AXI_16_WVALID;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 PCLK_0 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PCLK_0, ASSOCIATED_BUSIF SAPB_0, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input APB_0_PCLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 PRST_0_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PRST_0_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input APB_0_PRESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 PCLK_1 CLK" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PCLK_1, ASSOCIATED_BUSIF SAPB_1, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN qdma_hbm_bd_clk_wiz_0_0_clk_out1, INSERT_VIP 0" *) input APB_1_PCLK /* synthesis syn_isclock = 1 */;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 PRST_1_N RST" *) (* X_INTERFACE_MODE = "slave" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME PRST_1_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *) input APB_1_PRESET_N;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI ARREADY" *) output AXI_15_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI AWREADY" *) output AXI_15_AWREADY;
  output [31:0]AXI_15_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RDATA" *) output [255:0]AXI_15_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RID" *) output [5:0]AXI_15_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RLAST" *) output AXI_15_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RRESP" *) output [1:0]AXI_15_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI RVALID" *) output AXI_15_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI WREADY" *) output AXI_15_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI BID" *) output [5:0]AXI_15_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI BRESP" *) output [1:0]AXI_15_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_15_8HI BVALID" *) output AXI_15_BVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI ARREADY" *) output AXI_16_ARREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI AWREADY" *) output AXI_16_AWREADY;
  output [31:0]AXI_16_RDATA_PARITY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RDATA" *) output [255:0]AXI_16_RDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RID" *) output [5:0]AXI_16_RID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RLAST" *) output AXI_16_RLAST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RRESP" *) output [1:0]AXI_16_RRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI RVALID" *) output AXI_16_RVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI WREADY" *) output AXI_16_WREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI BID" *) output [5:0]AXI_16_BID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI BRESP" *) output [1:0]AXI_16_BRESP;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 SAXI_16_8HI BVALID" *) output AXI_16_BVALID;
  output apb_complete_0;
  output apb_complete_1;
  output DRAM_0_STAT_CATTRIP;
  output [6:0]DRAM_0_STAT_TEMP;
  output DRAM_1_STAT_CATTRIP;
  output [6:0]DRAM_1_STAT_TEMP;
endmodule
