# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/qdma_hbm_bd/qdma_hbm_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd || ORIG_REF_NAME==qdma_hbm_bd} -quiet] -quiet

# IP: bd/qdma_hbm_bd/ip/qdma_hbm_bd_hbm_0_0/qdma_hbm_bd_hbm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_hbm_0_0 || ORIG_REF_NAME==qdma_hbm_bd_hbm_0_0} -quiet] -quiet

# IP: bd/qdma_hbm_bd/ip/qdma_hbm_bd_smartconnect_0_0/qdma_hbm_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_smartconnect_0_0 || ORIG_REF_NAME==qdma_hbm_bd_smartconnect_0_0} -quiet] -quiet

# IP: bd/qdma_hbm_bd/ip/qdma_hbm_bd_clk_wiz_0_0/qdma_hbm_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_clk_wiz_0_0 || ORIG_REF_NAME==qdma_hbm_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/qdma_hbm_bd/ip/qdma_hbm_bd_proc_sys_reset_0_0/qdma_hbm_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qdma_hbm_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==qdma_hbm_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: /home/khanna/HBM/PCIe-HBM_basic-prj/vivado_gen/pcie-hbm_sim/pcie-hbm_sim.gen/sources_1/bd/qdma_hbm_bd/qdma_hbm_bd_ooc.xdc
